const sidebars = {
	tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  linux: [{
      type: 'autogenerated',
      dirName: 'linux',
    },
  ],
  mysql: [{
      type: 'autogenerated',
      dirName: 'mysql',
    },
  ],
  python: [{
      type: 'autogenerated',
      dirName: 'python',
    },
  ],
};

module.exports = sidebars;