const sidebars = {
	tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

	english: [{
		  type: 'autogenerated',
		  dirName: 'english',
		},
	],
	linux1: [{
		  type: 'autogenerated',
		  dirName: 'linux',
		},
	],
	  mysql: [{
		  type: 'autogenerated',
		  dirName: 'mysql',
		},
	  ],
	  python: [{
		  type: 'autogenerated',
		  dirName: 'python',
		},
	  ],
};

module.exports = sidebars;